[INPUT]
    Name                  tail
    Tag                   host.audit
    Path                  /var/log/audit/audit.log
    DB                    /var/lib/fluent-bit/audit.db
    Mem_Buf_Limit         10MB
    Skip_Long_Lines       On
    Refresh_Interval      5
    Read_From_Head        Off
    Path_Key              file

[INPUT]
    Name                  tail
    Tag                   host.auth
    Path                  /var/log/auth.log
    DB                    /var/lib/fluent-bit/auth.db
    Mem_Buf_Limit         5MB
    Skip_Long_Lines       On
    Refresh_Interval      5
    Read_From_Head        Off
    Path_Key              file

[FILTER]
    Name                  grep
    Match                 host.auth
    Regex                 log sshd|sudo|su|authentication failure|Failed password|Accepted password|Accepted publickey|Invalid user|pam_unix|session opened|session closed

[FILTER]
    Name                  record_modifier
    Match                 host.audit
    Record                collector fluent-bit
    Record                source ubuntu-audit

[FILTER]
    Name                  record_modifier
    Match                 host.auth
    Record                collector fluent-bit
    Record                source ubuntu-auth

[OUTPUT]
    Name                  http
    Match                 host.*
    Host                  ${SERVER_HOST}
    Port                  ${SERVER_PORT}
    URI                   /api/v1/logs
    Format                json
    Json_Date_Key         timestamp
    Json_Date_Format      iso8601
    Retry_Limit           False
#