[INPUT]
    Name                  tail
    Tag                   host.audit
    Path                  /var/log/audit/audit.log
    DB                    ${FLB_AUDIT_DB_PATH}
    DB.Sync               normal
    Mem_Buf_Limit         10MB
    Skip_Long_Lines       On
    Refresh_Interval      5
    Read_From_Head        Off
    Rotate_Wait           30
    Path_Key              file
    storage.type          filesystem

[INPUT]
    Name                  tail
    Tag                   host.auth
    Path                  /var/log/auth.log
    DB                    ${FLB_AUTH_DB_PATH}
    DB.Sync               normal
    Mem_Buf_Limit         5MB
    Skip_Long_Lines       On
    Refresh_Interval      5
    Read_From_Head        Off
    Rotate_Wait           30
    Path_Key              file
    storage.type          filesystem

[FILTER]
    Name                  grep
    Match                 host.auth
    Regex                 log sshd|sudo|su|authentication failure|Failed password|Accepted password|Accepted publickey|Invalid user|pam_unix|session opened|session closed

[FILTER]
    Name                  grep
    Match                 host.audit
    Exclude               log exe="/opt/fluent-bit/bin/fluent-bit"
    Exclude               log comm="flb-pipeline"

[FILTER]
    Name                  record_modifier
    Match                 host.audit
    Record                collector fluent-bit
    Record                source ubuntu-audit
    Record                client_id ${CLIENT_ID}
    Record                os linux

[FILTER]
    Name                  record_modifier
    Match                 host.auth
    Record                collector fluent-bit
    Record                source ubuntu-auth
    Record                client_id ${CLIENT_ID}
    Record                os linux

[OUTPUT]
    Name                  http
    Match                 host.*
    Host                  ${SERVER_HOST}
    Port                  ${SERVER_PORT}
    URI                   /api/v1/logs
    Format                json
    Json_Date_Key         timestamp
    Json_Date_Format      iso8601
    Retry_Limit           False
#
